# Copyright 2025 dah4k
# SPDX-License-Identifier: EPL-2.0

FROM zeek/zeek:latest AS zeek

ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=Etc/UTC
RUN apt-get update --quiet=2 --assume-yes --no-install-recommends \
 && apt-get install --quiet=2 --assume-yes --no-install-recommends \
        clamav \
        curl \
        jq \
        ripgrep \
        vim \
        zstd \
 && apt-get clean \
 && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

WORKDIR /app

