# Copyright 2025 dah4k
# SPDX-License-Identifier: EPL-2.0

FROM opensuse/tumbleweed:latest AS data

RUN zypper --quiet --non-interactive refresh \
 && zypper --quiet --non-interactive install --no-recommends \
        clamav \
        curl \
        jq \
        ripgrep \
        suricata \
        vim \
        vim-data \
        zstd \
 && zypper --quiet --non-interactive clean

RUN freshclam && suricata-update

ARG PCAP_DIR="/data/pcaps"
ARG LOG_DIR="/data/logs"
ARG QUARANTINE_DIR="/data/QUARANTINE"

RUN mkdir -p $PCAP_DIR $LOG_DIR $QUARANTINE_DIR

COPY config/suricata.yaml /etc/suricata/suricata.yaml
COPY config/file-store-all.rules /etc/suricata/rules/file-store-all.rules

WORKDIR /app

COPY process_pcap_files.sh /app/process_pcap_files.sh

WORKDIR /data

ENTRYPOINT ["/app/process_pcap_files.sh"]
CMD ["$PCAP_DIR", "$LOG_DIR", "$QUARANTINE_DIR"]
